server:
  port: 8082
  servlet:
    context-path: /cpst-scrum

spring:
  application:
    name: cpst-scrum

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/