server:
  port: 8081
  servlet:
    context-path: /cpst

spring:
  application:
    name: cpst-scrum
  jpa:
    open-in-view: false

security:
  oauth2:
    client:
      client-id: admin
      client-secret: Cpst@123
      scope:
        - password